Introduce rmc::proof function attribute (#668)
* Introduce rmc::proof function attribute

* add no_mangle as temporary measure to force function codegen

diff --git a/scripts/rmc-rustc b/scripts/rmc-rustc
--- a/scripts/rmc-rustc
+++ b/scripts/rmc-rustc
@@ -45,6 +45,16 @@ set_rmc_lib_path() {
         fi
         RMC_LIB_PATH=$(dirname ${RMC_LIB_CANDIDATES[0]})
     fi
+    # Having set RMC_LIB_PATH, find RMC_MACRO_LIB_PATH
+    local MACRO_LIB_CANDIDATE=(${RMC_LIB_PATH}/deps/librmc_macros-*)
+    if [[ ${#MACRO_LIB_CANDIDATE[@]} -ne 1 ]]
+    then
+        echo "ERROR: Could not find RMC library."
+        echo "Looked for: \"${RMC_LIB_PATH}/deps/librmc_macros-*\""
+        echo "Was RMC library successfully built first?"
+        exit 1
+    fi
+    RMC_MACRO_LIB_PATH="${MACRO_LIB_CANDIDATE[0]}"
 }
 
 set_rmc_path
@@ -58,8 +68,13 @@ else
             -Z trim-diagnostic-paths=no \
             -Z human_readable_cgu_names \
             --cfg=rmc \
+            -Zcrate-attr=feature(register_tool) \
+            -Zcrate-attr=register_tool(rmctool) \
             -L ${RMC_LIB_PATH} \
-            --extern rmc"
+            --extern rmc \
+            -L ${RMC_LIB_PATH}/deps \
+            --extern librmc_macros=${RMC_MACRO_LIB_PATH} \
+            "
     if [ "${1:-''}" == "--rmc-flags" ]
     then
         echo ${RMC_FLAGS}
